### ISSUE TITLE
Problem with the module

### ISSUE THREAD

**Issue by Yanmar2200** [simplifycom/simplify-prestashop-module#4]
I have installed the release 2.0.1 to prestashop 1.7.6.5 and when a customer make an order to my website write his name in Greek. The module complete the customer informatio automated and this has the result to appear the name as html code. This is a problem .

In addition how I can change the translation text in the frontpage of the module ?

Thanks a lot for your reply

**Comment by JohnbConneely** [comment]
Hey @Yanmar2200 we are currently working on fixing this and will be releasing it with one of the next versions of Prestashop. 

If the release does not fix your issue, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
