### ISSUE TITLE
can't test on localhost

### ISSUE THREAD

**Issue by mikecc444** [simplifycom/simplify-prestashop-module#5]
I can't test on localhost.
After clicking the Submit order button on the checkout page, the page is reloaded with the following params ?step=3&simplify_error=There%20was%20a%20problem%20with%20your%20payment:%20SSL%20certificate%20problem:%20self%20signed%20certificate%20in%20certificate%20chain#simplify_error

There are no errors in the console. Prestashop is vers 1.7.6.3.
I installed a self signed certificate, but there is no difference.

**Comment by JohnbConneely** [comment]
Hey @mikecc444,

Are you still encountering this issue? If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
